version: '3.8'

services:
  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "obusor", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - learning

  gin-gorm-crud:
    image: obusorezekiel/gin-gorm-crud-2:latest
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - learning

networks:
  learning:
    driver: bridge
