version: '3.8'

services:
  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "obusor", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - learning

  gin-1:
    build: .
    image: obusorezekiel/gin-gorm-crud-2:latest
    env_file:
      - .env
    ports:
      - "8081:8888"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - learning

  gin-2:
    build: .
    image: obusorezekiel/gin-gorm-crud-2:latest
    env_file:
      - .env
    ports:
      - "8082:8888"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - learning

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - gin-1
      - gin-2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - learning

networks:
  learning:
    driver: bridge

