apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: student-api
data:
  DATABASE_NAME: postgres
  DATABASE_USERNAME: obusor

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: student-api
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      nodeSelector:
        type: application
      containers:
        - name: db-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: student-api
spec:
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
