apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname.name }}
  namespace: {{ .Values.appname.namespace }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel | default "student-app" }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel | default "student-app" }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.appimage.repository | default "obusorezekiel/gin-gorm-crud" }}:{{ .Values.appimage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.appimage.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appconfigMapName | default "app-config" }}
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appconfigMapName | default "app-config" }}
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appconfigMapName | default "app-config" }}
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appconfigMapName | default "app-config" }}
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appsecretName | default "app-secrets" }}
                  key: DATABASE_PASSWORD
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
