apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname.name }}
  namespace: {{ .Values.appname.name }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | b64enc }}
