apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.dbconfigMapName }}
    namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
data:
    DATABASE_HOST: {{ .Values.database.host }}
    DATABASE_NAME: {{ .Values.database.name }}
    DATABASE_USERNAME: {{ .Values.database.username }}