apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.secrets.namespace }}
type: {{ .Values.secrets.type }}
data:
  DATABASE_PASSWORD: {{ .Values.secrets.data.DATABASE_PASSWORD }}