---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
type: {{ .Values.secret.type }}
data:
  DATABASE_PASSWORD: {{ .Values.secret.data.DATABASE_PASSWORD }}

