name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2 

      # Build API
      - name: Build API
        run: |
          go mod download
          go build -o ./bin/gin-gorm-crud 

      # Run tests
      # - name: Run tests
      #   run: go test -v ./...

      # Perform code linting
      - name: Lint code
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Retrieve version from the latest Git tag
      - name: Get version
        id: get_version
        run: |
          echo "VERSION_TAG=v1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    
      # Docker build and push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ env.VERSION_TAG }}

  update-deployment:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Get Image Tag
        id: tag
        run: echo ::set-output name=tag::${{ github.sha }}
        
      - name: Checkout code
        uses: actions/checkout@v3

       # Retrieve version from the latest Git tag
      - name: Get version
        id: get_version
        run: |
          echo "VERSION_TAG=v1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Update Tag in Values YAML
        run: |
          sed -i "s|apptag:.*|apptag: VERSION_TAG|g" helm/my-go/values.yaml
          cat helm/my-go/values.yaml
        env:
          github_token: ${{ secrets.GH_PAT }}

      - name: Commit changes
        run: |
          git config --global user.email "ci-bot@argocd.com"
          git config --global user.name "ci-bot"
          git add helm/my-go/values.yaml    
          git commit -m "Update image tag [skip ci]"
        env:
          github_token: ${{ secrets.GH_PAT}}
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT}}
          branch: ${{ github.ref }}
    