name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2 

      # Build API
      - name: Build API
        run: |
          go mod download
          go build -o ./bin/gin-gorm-crud 

      # Run tests
      # - name: Run tests
      #   run: go test -v ./...

      # Perform code linting
      - name: Lint code
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Retrieve version from the latest Git tag
      - name: Get version
        id: get_version
        run: |
          version=$(git describe --tags --abbrev=0 || echo "latest")
          echo "VERSION=${version}" >> $GITHUB_ENV
    
      # Docker build and push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ env.VERSION }}
