name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.2 

    # Build API
    - name: Build API
      run: |
        go mod download
        go build -o /gin-gorm-crud

    # Run tests
    # - name: Run tests
    #   run: go test -v ./...

    # Perform code linting
    - name: Lint code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    # Docker login
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Docker build and push
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
